```{r}
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
```

```{r}
setwd("C:\\Users\\Faiza Jibril\\Downloads")
getwd()
install.packages("tidyverse")
install.packages("vioplot")
library(vioplot)
library(ggplot2)
library(imputeTS)
library(lubridate)
library(dplyr)
library(tseries)
library(forecast)
library(tidyverse)
install.packages("gridExtra")
library(gridExtra)
install.packages("randomForest")
library(randomForest)
df <- read.csv("WRFdata_May2018.csv", header = TRUE)
# summary(df,13)
dim(df)
# str(df,3)

```
```{r}
header <- df[1,]
weather <- df[4873:5183,]




weather <- rbind(header, weather)

View(weather)


```

```{r}
start <- 3
step <- 10
# Initialize output data frame
output <- data.frame(TSK=double(),
                     PSFC=double(),
                     U10=double(),
                     V10=double(),
                     Q2=double(),
                     RAINC=double(),
                     RAINNC=double(),
                     SNOW=double(),
                     TSLB=double(),
                     SMOIS=double(),
                     date=character(),
                     stringsAsFactors=FALSE)

location <- data.frame(lat=character(),
                       long=character(),
                       stringsAsFactors=FALSE)
x <- 1
y <- nrow(weather)-1
s <- y-x


```
```{r}
# Loop over columns in weather data frame, skipping the first two
for (i in seq(from=start, to=ncol(weather), by=step)) {
  # Get date from column header
  date <- colnames(weather)[i]
  # Subset weather data frame to columns for this date
  subset <- weather[2:nrow(weather),i:(i+step-1)]
  # Add date column
  subset$date <- date
  # Rename columns
  colnames(subset) <- c("TSK", "PSFC", "U10" ,"V10", "Q2", "RAINC", "RAINNC", "SNOW", "TSLB", "SMOIS", "datetime")
  # Add subset to output data frame
  output <- rbind(output, subset)
  
  location[x:y,1] <- weather[2:nrow(weather),1]
  location[x:y,2] <- weather[2:nrow(weather),2]
  x <- y+1
  y <- x + s
}
output <- cbind(location, output)
```


```{r}
# Reorder columns
Glasgow <- output[,c("lat", "long", "U10" ,"V10", "TSK",  "PSFC", "Q2", "RAINC", "RAINNC", "SNOW", "TSLB", "SMOIS", "datetime")]

View(Glasgow)

```

```{r}
View(Glasgow)
dim(Glasgow)
str(Glasgow)
colnames(Glasgow)
sum(duplicated(Glasgow))
```
```{r}
# change the format of the datetime dataset
Glasgow$datetime <- gsub("X", "", Glasgow$datetime)
Glasgow$datetime <- gsub(".", "-", Glasgow$datetime, fixed=T)

```
```{r}

#convert data type to appropriate data type for use in modellinng
Glasgow$lat <- as.numeric(Glasgow$lat)
Glasgow$long <- as.numeric(Glasgow$long)
Glasgow$TSK <- as.numeric(Glasgow$TSK)
Glasgow$TSK <- Glasgow$TSK- 273.15 # Convert from Kelvin to Celsius
Glasgow$PSFC <- as.numeric(Glasgow$PSFC)
Glasgow$U10 <- as.numeric(Glasgow$U10)
Glasgow$V10 <- as.numeric(Glasgow$V10)
Glasgow$Q2 <- as.numeric(Glasgow$Q2)
Glasgow$RAINC <- as.numeric(Glasgow$RAINC)
Glasgow$RAINNC <- as.numeric(Glasgow$RAINNC)
Glasgow$SNOW <- as.numeric(Glasgow$SNOW)
Glasgow$TSLB <- as.numeric(Glasgow$TSLB)
Glasgow$TSLB <- Glasgow$TSLB - 273.15 # Convert from Kelvin to Celsius
Glasgow$SMOIS <- as.numeric(Glasgow$SMOIS)
Glasgow$datetime <- as.POSIXct(Glasgow$datetime, format = "%d-%m-%Y-%H-%M")
View(Glasgow$datetime)
```
```{r}
sum(is.na(Glasgow))
#checking for proportion of missing values

prop_missing <- round(colMeans(is.na(Glasgow)) *100, 2)

print(prop_missing)

```
```{r}
df <- data.frame(variables = names(prop_missing),
                 prop_missing = prop_missing)
View(df)
# Create a bar plot

colors = c("red", "green", "blue", "orange", "maroon", "purple", "yellow", "pink", "brown", "gray", "cyan", "magenta", "violet")
ggplot(df, aes(x = variables, y = prop_missing)) +
  geom_bar(stat = "identity", fill = colors) + coord_flip() +
  labs(title = "Proportion of Missing Values by Variable in %",
       x = "Variable",
       y = "Proportion of Missing Values in %")
```
```{r}


Glasgow <- na_interpolation(Glasgow, option = "linear")

# Find max date time value without NA
max_datetime <- max(Glasgow$datetime[!is.na(Glasgow$datetime)])

# Fill NA values with maximum datetime+ 3hours - 
Glasgow$datetime[is.na(Glasgow$datetime)] <- max_datetime + hours(3)
sum(is.na(Glasgow))
  

```

```{r}
# Create new wind column, wind direction column
Glasgow <- Glasgow %>% mutate(wind_speed = sqrt(U10^2 + V10^2))
View(Glasgow)
# Select Lat and Long of focus
Glasgow_airport <- Glasgow %>%
  filter(lat == 55.837 & long == 3.104)

```
```{r}
Glasgow <- Glasgow[,-10]
n_hours <- nrow(Glasgow)
```
```{r}
#Histogram
ggplot(Glasgow_airport, aes(x = wind_speed)) +
  geom_histogram(fill = "#3456FF", color = "black", bins = 30) +
  labs(title = "Histogram: WIND SPEED", x = "WIND SPEED (째m/s)", y = "Count") +
  theme_classic()

#Density Plot

ggplot(Glasgow_airport, aes(x = wind_speed)) +
  geom_density(fill = "#4786FF", color = "black") +
  labs(title = "Density Plot: Wind Speed", x = "Wind Speed (m/s)", y = "Density") +
  theme_classic()
```

```{r}
sum(is.na(Glasgow_airport))
View(Glasgow_airport)
Glasgow_airport$Year <-  as.numeric(format(Glasgow_airport$datetime, "%Y"))
Glasgow_airport$Month<-  as.numeric(format(Glasgow_airport$datetime, "%m"))
Glasgow_airport$Day<-  as.numeric(format(Glasgow_airport$datetime, "%d"))
Glasgow_airport$Hour <-  as.numeric(format(Glasgow_airport$datetime, "%H"))

```
```{r}
#delete unneccessary columns and reorder columns
Glasgow_airport <- subset(Glasgow_airport, select = -c(U10, V10))
Data2 <- Glasgow_airport
Glasgow_airport <- Glasgow_airport %>% 
  select(-wind_speed) %>% 
  mutate(wind_speed = Data2$wind_speed) %>% 
  select(1:2, wind_speed, 3:ncol(.))
```
```{r}
#Install and load the descr package and describe dataset
install.packages("psych")
library(psych)
psych::describe(Glasgow_airport)

```
```{r}
# Univariate analysis
par(mfrow = c(3, 2)) # 4 rows, 2 columns
par(mar = c(2, 2, 1, 1)+0.1) # bottom, left, top, right margins

# Define a function to generate boxplots
box_fun <- function(col, name) {
  boxplot(col, main = paste("Boxplot of", name), col = "blue")
}

# Use apply to generate list of boxplots
boxplots <- lapply(c(3,4,5,6), function(i) box_fun(Glasgow_airport[[i]], names(Glasgow_airport)[i]))
par(mfrow = c(2, 2))
boxplots <- lapply(c(9,10,11), function(i) box_fun(Glasgow_airport[[i]], names(Glasgow_airport)[i]))

```
```{r}

# Define a function to generate histograms
hist_fun <- function(col, name) {
  hist(col, main = paste("Histplot of", name), col = "pink")
}
par(mfrow = c(2, 2))
# Use apply to generate list of histograms
histograms <- lapply(names(Glasgow_airport)[3:6], function(name) hist_fun(Glasgow_airport[[name]], name))


# Bivariate analysis
par(mfrow = c(3, 3))
install.packages("DataExplorer")
library(DataExplorer)
scp <- plot_scatterplot(Glasgow_airport[,3:10], by = "wind_speed", sampled_rows = 10000L)


```
```{r}
# Use apply to generate list of correlations between mpg and all other variables except the last one

install.packages("corrplot")
library(corrplot)
View(Glasgow_airport)
par(mfrow = c(1, 1))
corrs <- cor(Glasgow_airport[, 3:10], use = "complete.obs")
corrs[is.na(corrs)] <- 0
corrplot(corrs, method = "circle")

```

```{r}
for (i in 1:ncol(Glasgow_airport)) {
  data <- Glasgow_airport[[i]]
  IQR_value <- IQR(data)
  Q1 <- quantile(data, 0.25)
  Q3 <- quantile(data, 0.75)
  lower_bound <- Q1 - 1.5 * IQR_value
  upper_bound <- Q3 + 1.5 * IQR_value
  outliers <- data[data < lower_bound | data > upper_bound]
  data[data < lower_bound | data > upper_bound] <- NA
  Glasgow_airport[[i]] <- na.interpolation(data)
}

```

```{r}
ggplot(Glasgow_airport, aes(x = "", y = wind_speed)) +
  geom_boxplot(width = 0.3, fill = "purple", alpha = 0.5) + geom_density(alpha = 0.3) +
  labs(title = "Box Plot: WIND SPEED", y = "WIND SPEED (째C)") +
  theme_grey()

ggplot(Glasgow_airport, aes(x = "", y = PSFC)) +
  geom_boxplot(width = 0.3, fill = "light blue", alpha = 0.5) + 
  labs(title = "Box Plot: SURFACE PRESSURE", y = "SURFACE PRESSURE (째Pa)") +
  theme_grey()

ggplot(Glasgow_airport, aes(x = "", y = Q2)) +
  geom_boxplot(width = 0.3, fill = "light pink", alpha = 0.5) + geom_density(alpha = 0.3) +
  labs(title = "Box Plot: Humidity ", y = "Humidity (째Kg)") +
  theme_grey()

```


```{r}

# Time series of Wind Speed

ggplot(Glasgow_airport, aes(x = datetime, y = wind_speed)) +
  geom_line(color = "blue") +
  labs(title = "Wind Speed Over Time",
       x = "Date and Time",
       y = "WIND SPEED") +
  theme_minimal()
```
```{r}
# Create timestep variable 

View(Glasgow_airport)
Glasgow_airport <- Glasgow_airport %>%
  mutate(time = as.numeric(difftime(datetime, min(datetime), units = "hours")))
View(Glasgow_airport)



```

```{r}
# Split the data into training and test sets
set.seed(123)
train_indices <- sample(1:nrow(Glasgow_airport), 0.8 * nrow(Glasgow_airport))
train_data <- Glasgow_airport[train_indices, ]
test_data <- Glasgow_airport[-train_indices, ]

```
```{r}
# Create timeseries dataset for ARIMA training and testing
Glasgow_airport_ts<- ts (Glasgow_airport$wind_speed, start = c(2018, 5), frequency = 8 * 31)
View(Glasgow_airport_ts)
# Determine the index of the last observation in the training set
n_times <- length(Glasgow_airport_ts)

train_end_idx <- nrow(train_data)

train_data_ts <- Glasgow_airport_ts [1: train_end_idx]
test_data_ts <- Glasgow_airport_ts[(train_end_idx + 1):length(Glasgow_airport_ts)]


```
```{r}
# Fit the ARIMA model
arima_model<-auto.arima(train_data_ts)
# Forecast using the ARIMA model

arima_forecast<-forecast(arima_model,h=length(test_data_ts))
print(arima_model)

```
```{r}
# Calculate the Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE)

rmse_arima <- sqrt(mean((test_data_ts - arima_forecast$mean)^2))
# Display the performance metrics
cat("RMSE =", rmse_arima, "\n")
```
```{r}
#Model diagnostics for ARIMA model
checkresiduals (arima_model)

# Plot histogram of residuals
hist(arima_model$residuals, main = "Histogram of ARIMA Model Residuals", xlab = "Residuals", col ="lightblue")


```


```{r}
# Create a linear regression model

regression_model <- lm(wind_speed ~ time, data = train_data)
summary(regression_model)

# Predict wind_speed values for the test set
reg_predictions <- predict(regression_model, newdata = test_data)

```

```{r}
# Calculate the root mean squared error (RMSE)
reg_rmse <- sqrt(mean((test_data$wind_speed - reg_predictions)^2))

cat("Standard Regression Model: RMSE=", reg_rmse)
```
```{r}


```

```{r}

```



```{r}
# SUPPORT VECTOR MACHINE
install.packages("e1071")
library(e1071)
# Fit an SVM model on the training set
svm_radial <- svm(wind_speed ~ time, data = train_data, kernel = "radial")
# Display the SVM model summary
summary(svm_radial)
# Predict wind speed values for the test set using the SVR model
svm_radial_predictions <- predict(svm_radial, newdata = test_data)

# Calculate the root mean squared error (RMSE) for the SVR model
svr_rmse_radial <- sqrt(mean((test_data$wind_speed - svm_radial_predictions)^2))
cat("SVR RMSE for Radial Kernel:", svr_rmse_radial)

```
```{r}
svm_linear <- svm(wind_speed ~ time, data = train_data, kernel = "linear")
summary(svm_linear)
# Predict wind speed values for the test set using the SVR linear model 
linear_predictions <- predict(svm_linear, newdata = test_data)


svm_linear_rmse <- sqrt(mean((test_data$wind_speed - linear_predictions)^2))
cat("SVR Linear RMSE:", svm_linear_rmse)

```
```{r}
# Fit a polynomial SVM model
svm_poly <- svm(wind_speed ~ time, data = train_data, kernel = "polynomial", degree = 2)
summary(svm_poly)
# Predict wind speed values for the test set using the SVR linear model 
poly_predictions <- predict(svm_poly, newdata = test_data)

svr_poly_rmse <- sqrt(mean((test_data$wind_speed - poly_predictions)^2))
cat("SVR Poly RMSE:", svr_poly_rmse)

```
```{r}
# create a df to hold the rmse values
rmse_comparison_SVR <- data.frame(
  svr_model = c("SVR Linear", "SVR Radial", "SVR Poly"),
  RMSE = c(svm_linear_rmse, svr_rmse_radial, svr_poly_rmse)
)

# create a bar chart to visualize the rmse scores of the SVM models
ggplot(rmse_comparison_SVR, aes(x = svr_model, y = RMSE, fill = svr_model)) +
  geom_bar(stat = "identity", width = 0.3) +
  labs(title = "Root Mean Square Errors of SVR Models",
       x = "SVM Model",
       y = "Root Mean Square Error") +
  theme_minimal() +
  scale_fill_manual(values = c("SVR Linear" = "pink", "SVR Radial" = "brown", "SVR Polynomial" = "yellow")) +
  theme(legend.position = "none")
```
```{r}
# Plot the actual vs. predicted values for the linear regression and SVR models
p1 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = svm_linear_rmse), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "pink") +
  labs(title = "Linear SVR: Actual vs. Predicted Wind Speed",
       x = "Wind Speed",
       y = "Predicted Wind Speed") +
  theme_minimal()

p2 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = svm_radial_predictions), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  labs(title = "Radial SVR : Actual vs. Predicted Wind Speed",
       x = "Wind Speed",
       y = "Predicted Wind Speed") +
  theme_minimal()

p3 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y =svr_poly_rmse), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "orange") +
  labs(title = "Polynomial SVR : Actual vs. Wind Speed",
       x = "Actual Wind Speed",
       y = "Predicted Wind Speed ") +
  theme_minimal()

grid.arrange(p1, p2, p3, ncol = 3)

```
```{r}
# RANDOM FOREST


# Fit a Random Forest model on the training set ntree =100
rf_model_100 <- randomForest(wind_speed ~ time, data = train_data, ntree = 100)
# Display the Random Forest model summary
summary(rf_model_100)
# Predict wind speed values for the test set using the Random Forest model
rf_predictions_100 <- predict(rf_model_100, newdata = test_data)


# Calculate the RMSE
rf_rmse_100 <- sqrt(mean((test_data$wind_speed - rf_predictions_100)^2))
cat("Random Forest RMSE 100:", rf_rmse_100)


```
```{r}
# Fit a Random Forest model on the training set ntree =250
rf_model_250 <- randomForest(wind_speed ~ time, data = train_data, ntree = 250)
# Display the Random Forest model summary
summary(rf_model_250)
# Predict wind speed values for the test set using the Random Forest model
rf_predictions_250 <- predict(rf_model_250, newdata = test_data)
rf_rmse_250 <- sqrt(mean((test_data$wind_speed - rf_predictions_250)^2))
cat("Random Forest RMSE:", rf_rmse_250)

```
```{r}
# Fit a Random Forest model on the training set ntree =500
rf_model_500 <- randomForest(wind_speed ~ time, data = train_data, ntree = 500)
# Display the Random Forest model summary
summary(rf_model_500)
# Predict wind speed values for the test set using the Random Forest model
rf_predictions_500 <- predict(rf_model_500, newdata = test_data)


# Calculate the RMSE
rf_rmse_500 <- sqrt(mean((test_data$wind_speed - rf_predictions_500)^2))
cat("Random Forest RMSE 500:", rf_rmse_500)

```
```{r}

# create a df to hold the rmse values
rmse_comparison_RF<- data.frame(
  RF_model = c("RF 100 Trees", "RF 250 Trees", "RF 500 Trees"),
  RMSE = c(rf_rmse_100, rf_rmse_250, rf_rmse_500)
)

# create a bar chart to visualize the rmse scores of the RF models
ggplot(rmse_comparison_RF, aes(x = RF_model, y = RMSE, fill = RF_model)) +
  geom_bar(stat = "identity", width = 0.3) +
  labs(title = "Root Mean Square Errors of Random Forest Models",
       x = "Random Forest Model",
       y = "Root Mean Square Error") +
  theme_minimal() +
  scale_fill_manual(values = c("RF 100 Trees" = "pink", "RF 250 Trees" = "purple", "RF 500 Trees" = "lightblue")) +
  theme(legend.position = "none")

```

```{r}

# Plot the actual vs. predicted values for the linear regression and SVR models
p1 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = rf_rmse_100), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "pink") +
  labs(title = "Random Forest(ntree=100) Model: Actual vs. Predicted Wind Speed",
       x = "Wind Speed",
       y = "Predicted Wind Speed") +
  theme_minimal()
p2 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = rf_rmse_250), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "orange") +
  labs(title = "Random Forest(ntree=250) Model: Actual vs. Wind Speed",
       x = "Actual Wind Speed",
       y = "Predicted Wind Speed ") +
  theme_minimal()

p3 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = rf_rmse_500), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  labs(title = "Random Forest(ntree=500 model): Actual vs. Predicted Wind Speed",
       x = "Wind Speed",
       y = "Predicted Wind Speed") +
  theme_minimal()



grid.arrange(p1, p2, p3, ncol = 3)
```

```{r}
# Compare the RMSE values of the Arima, Linear Regression, SVR, and Random Forest models
cat("\nArima RMSE:", rmse_arima)
cat("\nLinear Regression RMSE:", reg_rmse)
cat("\nSVR RMSE:", svr_rmse_radial)
cat("\nRandom Forest RMSE:", rf_rmse_250)
```

```{r}
rmse_comparison_df <- data.frame(
  Model = c("ARIMA", "Linear Regression", "SVR Radial", "Random Forest (ntree=250)"),
  RMSE = c(rmse_arima, reg_rmse, svr_rmse_radial, rf_rmse_250)
)


# Bar chart to visualize the comparison
ggplot(rmse_comparison_df, aes(x = Model, y = RMSE, fill = Model)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(title = "Root Mean Square Error for Selected Models",
       x = "Model",
       y = "Mean Absolute Error") +
  theme_minimal() +
  scale_fill_manual(values = c("ARIMA" = "lightblue", "Linear Regression" = "maroon", "SVR Radial" = "lightpink", "Random Forest (ntree=250)" = "magenta")) +
  theme(legend.position = "none")
```
```{r}
p1 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = reg_predictions), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  labs(title = "Linear Regression: Actual vs. Predicted Wind Speed",
       x = "Wind Speed",
       y = "Predicted Wind Speed") +
  theme_minimal()

p2 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = svm_radial_predictions), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "orange") +
  labs(title = "Radial SVR: Actual vs. Wind Speed",
       x = "Actual Wind Speed",
       y = "Predicted Wind Speed ") +
  theme_minimal()

p3 <- ggplot() +
  geom_point(data = test_data, aes(x = wind_speed, y = rf_predictions_250), color = "blue") +
  geom_abline(slope = 1, intercept = 0, color = "lightblue") +
  labs(title = "Random Forest (ntree=250): Actual vs. Wind Speed",
       x = "Actual Wind Speed",
       y = "Predicted Wind Speed ") +
  theme_minimal()

grid.arrange(p1, p2, p3, ncol = 6)

```
```{r}
p1
```
```{r}
p2
```
```{r}
p3
```
```{r}
# Calculate the Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE)
mae_arima <- mean(abs(test_data_ts - arima_forecast$mean))
rmse_arima <- sqrt(mean((test_data_ts - arima_forecast$mean)^2))
cat("ARIMA Model: MAE=", mae_arima, ", RMSE =", rmse_arima, "\n")

```
```{r}

```
```{r}

```
```{r}

```
```{r}

# Calculate the mean absolute error (MAE)
rf_mae_500 <- mean(abs(test_data$wind_speed - rf_predictions_500))
cat("Random Forest_500 MAE :", rf_mae_500)
rf_rmse_500 <- sqrt(mean((test_data$wind_speed - rf_predictions_500)^2))
cat("Random Forest RMSE 500:", rf_rmse_500)
```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```

